import errno
errortext = {errno.EPERM:'Operation not permitted',
    errno.ENOENT:'No such file or directory',
    errno.EIO:'I/O error',
    errno.EBADF:'Bad file number',
    errno.EAGAIN:'Try again',
    errno.ENOMEM:'Out of memory',
    errno.EACCES:'Permission denied',
    errno.EEXIST:'File exists',
    errno.ENODEV:'No such device',
    errno.EISDIR:'Is a directory',
    errno.EINVAL:'Invalid argument',
    errno.EOPNOTSUPP:'Operation not supported on transport endpoint',
    errno.EADDRINUSE:'Address already in use',
    errno.ECONNABORTED:'Software caused connection abort',
    errno.ECONNRESET:'Connection reset by peer',
    errno.ENOBUFS:'No buffer space available',
    errno.ENOTCONN:'Transport endpoint is not connected',
    errno.ETIMEDOUT:'Connection timed out',
    errno.ECONNREFUSED:'Connection refused',
    errno.EHOSTUNREACH:'No route to host',
    errno.EALREADY:'Operation already in progress',
    errno.EINPROGRESS: 'Operation now in progress'}